# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  database: rails_test_development
  pool: 5
  timeout: 5000

# Warning: The database defined as "test" will be erased and
test:
  adapter: postgresql
  encoding: utf8
  database: rails_test_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: rails_test_production
  pool: 5
  timeout: 5000
